# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

cache: packages

r_github_packages: dickoa/rgeoboundaries

before_install:
  - sudo apt-get install libproj-dev libgeos++-dev
  - cd
  - wget http://download.osgeo.org/gdal/2.1.0/gdal-2.1.0.tar.gz
  - tar zxf gdal-2.1.0.tar.gz
  - cd gdal-2.1.0
  - ./configure
  - make
  - sudo make install

apt_packages:
  - libudunits2-dev

r_packages:
  - rgdal

warnings_are_errors: true

sudo: required

addons:
  apt:
    update: true

after_success:
    - Rscript -e 'covr::codecov()'
