# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

sudo: required

cache:
  - packages


addons:
  # postgresql: "10"
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
      - sourceline: 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'
        key_url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      # - postgresql-server-dev-9.6
      # - postgis

before_install:
  - R -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org")'

r_github_packages: dickoa/rgeoboundaries

after_success:
    - Rscript -e 'covr::codecov()'
