# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

cache: packages

apt_packages:
  - libudunits2-dev

before_install:
  - sudo apt-get install libproj-dev libgeos++-dev
  - cd
  - wget https://github.com/OSGeo/gdal/releases/download/v3.1.2/gdal-3.1.2.tar.gz
  - tar zxf gdal-3.1.2.tar.gz
  - cd gdal-3.1.2
  - ./configure
  - make
  - sudo make install

warnings_are_errors: true

r_packages:
  - rgdal
  - roxygen2
  - rmarkdown

r_github_packages: dickoa/rgeoboundaries

after_success:
    - Rscript -e 'covr::codecov()'
