# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

cache: packages

r_github_packages: dickoa/rgeoboundaries

addons:
  apt:
    packages:
      - libudunits2-dev

after_success:
    - Rscript -e 'covr::codecov()'
